ccvpn/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

from . import views

from lambdainst import urls as account_urls, views as account_views
from payments import urls as payments_urls
from tickets import urls as tickets_urls

urlpatterns = [
    url(r'^admin/status$', account_views.admin_status, name='admin_status'),
    url(r'^admin/referrers$', account_views.admin_ref, name='admin_ref'),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^api/locations$', account_views.api_locations),
    url(r'^api/auth$', account_views.api_auth),

    url(r'^$', views.index, name='index'),
    url(r'^ca.crt$', account_views.ca_crt),
    url(r'^setlang$', views.set_lang, name='set_lang'),
    url(r'^chat$', views.chat, name='chat'),
    url(r'^page/(?P<name>[a-zA-Z0-9_-]+)$', views.page, name='page'),
    url(r'^status$', account_views.status),

    url(r'^account/forgot$', auth_views.password_reset,
        {}, name='password_reset'),
    url(r'^account/forgot_done$', auth_views.password_reset_done,
        name='password_reset_done'),
    url(r'^account/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^account/reset/done/$', auth_views.password_reset_complete,
        name='password_reset_complete'),

    url(r'^account/', include(account_urls, namespace='account')),
    url(r'^payments/', include(payments_urls, namespace='payments')),
    url(r'^tickets/', include(tickets_urls, namespace='tickets')),

]

tickets/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^new$', views.new, name='new'),
    url(r'^view/(?P<id>[0-9]+)$', views.view, name='view'),
    url(r'^$', views.index, name='index'),
    url(r'^open$', views.index, dict(f='open'), name='index_open'),
    url(r'^closed$', views.index, dict(f='closed'), name='index_closed'),
    url(r'^all_open$', views.index, dict(f='open', all=True), name='index_open_all'),
    url(r'^all_closed$', views.index, dict(f='closed', all=True), name='index_closed_all'),
]

ccvpn/views.py
import os.path

import markdown
from django.http import HttpResponseNotFound
from django.shortcuts import render
from django.conf import settings
from django.utils.translation import ugettext as _, get_language
from django import http
from django.utils.http import is_safe_url
from django.utils.translation import (
    LANGUAGE_SESSION_KEY, check_for_language,
)
from constance import config

from .common import get_price_float


md = markdown.Markdown(extensions=['toc', 'meta', 'codehilite(noclasses=True)'])


def index(request):
    eur = '%.2f' % get_price_float()
    return render(request, 'ccvpn/index.html', dict(eur_price=eur, motd=config.MOTD))


def chat(request):
    if request.user.is_authenticated():
        username = request.user.username + '|cc'
    else:
        username = "cc?"
    ctx = dict(username=username, title=_("Live Chat"))
    return render(request, 'ccvpn/chat.html', ctx)


def set_lang(request):
    """ django.views.i18n.set_language() with GET """

    next = request.GET.get('next', request.GET.get('next'))
    if not is_safe_url(url=next, host=request.get_host()):
        next = request.META.get('HTTP_REFERER')
        if not is_safe_url(url=next, host=request.get_host()):
            next = '/'
    response = http.HttpResponseRedirect(next)
    lang_code = request.GET.get('lang', None)
    if lang_code and check_for_language(lang_code):
        if hasattr(request, 'session'):
            request.session[LANGUAGE_SESSION_KEY] = lang_code
        else:
            response.set_cookie(settings.LANGUAGE_COOKIE_NAME, lang_code,
                                max_age=settings.LANGUAGE_COOKIE_AGE,
                                path=settings.LANGUAGE_COOKIE_PATH,
                                domain=settings.LANGUAGE_COOKIE_DOMAIN)
    return response


def page(request, name):
    basename = settings.PAGES_DIR + '/' + name

    username = request.user.username

    page_replace = {
        'USERNAME': username or '[username]',
    }

    files = [
        basename + '.' + get_language() + '.md',
        basename + '.en.md',
        basename + '.md',
    ]

    for file in files:
        if not os.path.isfile(file):
            continue

        with open(file, encoding='utf8') as fh:
            page = fh.read()
            for s, r in page_replace.items():
                page = page.replace('{' + s + '}', r)
            page = md.convert(page)

            title = md.Meta.get('title', [None])[0]
            ctx = dict(content=page, title=title)
            return render(request, 'ccvpn/page.html', ctx)

    return HttpResponseNotFound()

templates/ccvpn/chat.html
{% extends 'layout.html' %}
{% load i18n %}
{% load staticfiles %}


{% block wrap %}
    {% url 'tickets:new' as new_ticket %}
    <div id="livechat-info">
        <p>{% blocktrans trimmed with new_ticket as new_ticket %}
            We're not able to chat all the time for now.
            If we don't reply, please <a href="{{new_ticket}}">open a support ticket</a>
            and we will get back to you as soon as possible!
            {% endblocktrans %}
        </p>
    </div>

    <iframe id="livechat-iframe" src="https://vpn.ccrypto.org/kiwi/?nick={{username}}&theme=ccrelaxed#ccrypto"></iframe>

    <script type="text/javascript">
        (function() {
            function resize() {
                var h = (document.body.offsetHeight
                         - document.getElementById("topbar").offsetHeight
                         - document.getElementById("header").offsetHeight
                         - document.getElementById("footer").offsetHeight
                         - document.getElementById("livechat-info").offsetHeight
                         - 10);
                console.log(h);
                document.getElementById("livechat-iframe").style.height = h + "px";
            }
            window.addEventListener("load", resize);
            window.addEventListener("resize", resize);
        })();
    </script>
{% endblock %}

{# Remove the blue live chat link in the corner #}
{% block livechat_thing %}
{% endblock %}

templates/ccvpn/index.html
{% extends 'layout.html' %}
{% load i18n %}
{% load staticfiles %}

{% block headers %}
    <meta name="description" content="{% trans 'CCrypto VPN is a cheap, fast, anonymous and secure VPN service' %}" />
{% endblock %}

{% block content %}
<div class="content">
    <div class="pure-g home-content">
        <div class="home-item pure-u-1 pure-u-md-1-5">
            <img src="{% static 'img/unlimited.svg' %}" alt="" />
            <div class="home-item-content">
                <h2>{% trans 'Unlimited' %}</h2>
                <p><b>{% trans 'Unlimited bandwidth' %}</b>.<br />
                    <b>{% trans 'Uncensored' %}</b>.<br />
                    {% trans 'The data must flow.' %}</p>
            </div>
        </div>
        <div class="home-item pure-u-1 pure-u-md-1-5">
            <img src="{% static 'img/cheap.svg' %}" alt="" />
            <div class="home-item-content">
                <h2>{% trans 'Cheap' %}</h2>
                <p><b>{{eur_price}}&euro;</b> {% trans 'per month!' %}<br/>
                    {% trans 'We accept Paypal, Bitcoins and Stripe.' %}</p>
            </div>
        </div>
        <div class="home-item pure-u-1 pure-u-md-1-5">
            <img src="{% static 'img/anon.svg' %}" alt="" />
            <div class="home-item-content">
                <h2>{% trans 'Secure' %}</h2>
                <p><b>{% trans 'Encrypted tunnel' %}</b>
                    {% trans 'with an <b>anonymous address</b>.' %}<br />
                    {% trans 'Supports DNSSEC and PFS.' %}</p>
            </div>
        </div>
        <div class="home-item pure-u-1 pure-u-md-1-5">
            <img src="{% static 'img/openvpn.svg' %}" alt="" />
            <div class="home-item-content">
                <h2>{% trans 'OpenVPN' %}</h2>
                <p>{% trans 'Secure, Free, easy. On:' %}<br/>
                    <ul>
                        <li><b>Windows, OSX</b></li>
                        <li><b>GNU/Linux, BSD</b></li>
                        <li><b>Android, iOS</b></li>
                    </ul>
                </p>
            </div>
        </div>
        <div class="home-item pure-u-1 pure-u-md-1-5">
            <img src="{% static 'img/fast.svg' %}" alt="" />
            <div class="home-item-content">
                <h2>{% trans 'Fast' %}</h2>
                <p><b>1Gbps</b><br/>
                    <b>{% trans 'Compressed tunnel.' %}</b><br />
                    {% trans 'Even on YouTube.' %}
                </p>
            </div>
        </div>
        <div style="clear: both"></div>
    </div>

    <p class="home-signup">
        <a href="/account/signup" class="home-signup-button pure-button pure-button-primary">
            {% trans 'Sign up and get your free trial' %}
        </a>
    </p>

    <div class="pure-g">
        <div class="pure-u-1 pure-u-md-1-2 newhomehalf">
            <h2>{% trans 'Why?' %}</h2>
            <ul>
                <li>{% trans 'Hide any personal data found from your IP address' %}</li>
                <li>{% trans 'Protect yourself on open networks' %}</li>
                <li>{% trans 'Compress traffic on slow connections' %}</li>
                <li>{% trans 'Bypass overly restrictive firewalls' %}</li>
                <li>{% trans 'Enable IPv6 on IPv4-only networks' %}</li>
            </ul>
        </div>
        <div class="pure-u-1 pure-u-md-1-2 newhomehalf">
            <h2>{% trans 'VPN done the right way' %}</h2>
            <ul>
                <li><b>{% trans 'Anonymity' %}</b> - {% trans "We don't even require your email address." %}</li>
                <li><b>{% trans 'Security' %}</b> - {% trans "Best TLS available, RSA 4096b, BlowFish 128b." %}</li>
                <li><b>{% trans 'Privacy' %}</b> - {% trans "Not a single byte of your traffic is logged." %}</li>
            </ul>
        </div>
    </div>

</div>

{% endblock %}

templates/ccvpn/page.html
{% extends 'layout.html' %}
{% load i18n %}
{% load staticfiles %}

{% block content %}
<div class="page">
    <div class="left-menu">
        <p class="menu-title">{% trans 'Help' %}</p>
        <ul>
            <li><a href="/page/faq">{% trans 'Frequently Asked Questions' %}</a></li>
            <li><a href="/page/self-diagnosis">{% trans 'Self-Diagnosis' %}</a></li>
        </ul>

        <p class="menu-title">{% trans 'Installation' %}</p>
        <ul>
            <li><a href="/page/install-android">{% trans 'Android' %}</a></li>
            <li><a href="/page/install-windows">{% trans 'Windows' %}</a></li>
            <li><a href="/page/install-gnulinux">{% trans 'GNU/Linux' %}</a></li>
            <li><a href="/page/install-osx">{% trans 'OS X' %}</a></li>
        </ul>
    </div>
    <div class="content">
        {% if title %}
            <h1>{{ title }}</h1>
        {% endif %}
        {{ content|safe }}
    </div>
</section>
{% endblock %}

templates/ccvpn/require_email.html
{% extends 'layout.html' %}
{% load i18n %}
{% load staticfiles %}

{% block content %}
<div class="content formpage signuppage pure-g">
    <div class="pure-u-1 pure-u-sm-1-2 pure-u-xl-1-3">
        <h1>{% trans 'E-mail Confirmation' %}</h1>
        <form class="pure-form pure-form-stacked" action="" method="post">
            {% csrf_token %}

            {{ form.email.errors }}
            <label for="email">{% trans 'E-Mail' %}</label>
            <input type="email" id="email" name="email" value="{{email}}" />
            <p class="inputhelp">
                <b>{% trans 'Required to use the forums. A confirmation will be sent.' %}</b>
            </p>

            <input type="submit" class="pure-button pure-button-primary" value="{% trans 'Continue' %}" />
        </form>
    </div>
</div>

{% endblock %}

templates/ccvpn/signup.html
{% extends 'layout.html' %}
{% load i18n %}
{% load staticfiles %}

{% block content %}
<div class="content formpage signuppage pure-g">
    <div class="pure-u-1 pure-u-sm-1-2 pure-u-xl-1-3">
        <h1>{% trans 'Sign up' %}</h1>
        <form class="pure-form pure-form-stacked" action="/account/signup" method="post">
            {% csrf_token %}

            {{ form.username.errors }}
            <label for="username">{% trans 'Username' %}</label>
            <input type="text" id="username" name="username" pattern="[a-zA-Z0-9_-]{2,16}"
                   required="required" value="{{username}}" />
            <p class="inputhelp">{% trans '2 to 32 alphanumeric characters.' %}</p>

            {{ form.password.errors }}
            <label for="password">{% trans 'Password' %}</label>
            <input type="password" id="password" name="password" required="required"
                   value="{{password}}" />
            <p class="inputhelp">{% trans 'Anything from 1 to 256 characters.' %}</p>

            <label for="password2">{% trans 'Repeat' %}</label>
            <input type="password" id="password2" name="password2" required="required"
                   value="{{password}}" />
            <p class="inputhelp">{% trans 'Same password.' %}</p>

            {{ form.email.errors }}
            <label for="email">{% trans 'E-Mail' %}</label>
            <input type="email" id="email" name="email" value="{{email}}" />
            <p class="inputhelp">
                <b>{% trans 'Optional.' %}</b>
                {% trans 'Used to recover your password and confirm stuff.' %}
            </p>

            <input type="submit" class="pure-button pure-button-primary" value="{% trans 'Sign up' %}" />
        </form>
        <div class="rightsignup links">
            <ul>
                <li><a href="/account/login">{% trans 'Already a member? Log in' %}</a></li>
                <li><a href="/account/forgot">{% trans 'Forgot your password?' %}</a></li>
                <li><a href="/chat">{% trans 'Need help?' %}</a></li>
            </ul>
        </div>
    </div>
</div>

{% endblock %}