ccvpn/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

from . import views

from lambdainst import urls as account_urls, views as account_views
from payments import urls as payments_urls
from tickets import urls as tickets_urls

urlpatterns = [
    url(r'^admin/status$', account_views.admin_status, name='admin_status'),
    url(r'^admin/referrers$', account_views.admin_ref, name='admin_ref'),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^api/locations$', account_views.api_locations),
    url(r'^api/auth$', account_views.api_auth),

    url(r'^$', views.index, name='index'),
    url(r'^ca.crt$', account_views.ca_crt),
    url(r'^setlang$', views.set_lang, name='set_lang'),
    url(r'^chat$', views.chat, name='chat'),
    url(r'^page/(?P<name>[a-zA-Z0-9_-]+)$', views.page, name='page'),
    url(r'^status$', account_views.status),

    url(r'^account/forgot$', auth_views.password_reset,
        {}, name='password_reset'),
    url(r'^account/forgot_done$', auth_views.password_reset_done,
        name='password_reset_done'),
    url(r'^account/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^account/reset/done/$', auth_views.password_reset_complete,
        name='password_reset_complete'),

    url(r'^account/', include(account_urls, namespace='account')),
    url(r'^payments/', include(payments_urls, namespace='payments')),
    url(r'^tickets/', include(tickets_urls, namespace='tickets')),

]

tickets/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^new$', views.new, name='new'),
    url(r'^view/(?P<id>[0-9]+)$', views.view, name='view'),
    url(r'^$', views.index, name='index'),
    url(r'^open$', views.index, dict(f='open'), name='index_open'),
    url(r'^closed$', views.index, dict(f='closed'), name='index_closed'),
    url(r'^all_open$', views.index, dict(f='open', all=True), name='index_open_all'),
    url(r'^all_closed$', views.index, dict(f='closed', all=True), name='index_closed_all'),
]

tickets/models.py
from django.db import models
from django.conf import settings
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse
from django.template.loader import get_template
from django.template import Context
from django.core.mail import send_mail


ROOT_URL = settings.ROOT_URL
SITE_NAME = settings.TICKETS_SITE_NAME

CATEGORY_CHOICES = (
    ('support', _("Support")),
    ('security', _("Security")),
    ('billing', _("Account / Billing")),
)

if hasattr(settings, 'TICKETS_CATEGORIES'):
    CATEGORY_CHOICES = settings.TICKETS_CATEGORIES


def notify(subject, template, recipient_list, params):
    ctx = Context(dict(site_name=SITE_NAME, **params))
    text = get_template(template).render(ctx)

    for a in recipient_list:
        send_mail(subject, text, settings.DEFAULT_FROM_EMAIL, [a], fail_silently=True)


class Ticket(models.Model):
    class Meta:
        ordering = ('-created',)

        permissions = (
            ('view_any_ticket', _("Can view any ticket")),
            ('reply_any_ticket', _("Can reply to any ticket")),
            ('view_private_message', _("Can view private messages on tickets")),
            ('post_private_message', _("Can post private messages on tickets")),
        )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True,
                             on_delete=models.SET_NULL)
    category = models.CharField(max_length=16, choices=CATEGORY_CHOICES)
    subject = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    is_open = models.BooleanField(default=True)
    closed = models.DateTimeField(blank=True, null=True)

    @property
    def status_text(self):
        if self.closed:
            return _("Closed")
        last_msg = self.message_set.last()
        if last_msg and last_msg.user == self.user:
            return _("Waiting for staff")
        else:
            return _("Open")

    def get_contacts(self):
        contacts = TicketNotifyAddress.objects.filter(category=self.category)
        return [c.address for c in contacts]

    def notify_new(self, first_message):
        url = ROOT_URL + reverse('tickets:view', args=(self.id,))
        subject = _("Ticket:") + " " + self.subject
        ctx = dict(ticket=self, message=first_message, url=url)
        notify(subject, 'tickets/mail_support_new.txt', self.get_contacts(), ctx)

    def notify_reply(self, message):
        url = ROOT_URL + reverse('tickets:view', args=(self.id,))
        subject = _("Ticket:") + " " + self.subject
        ctx = dict(ticket=self, message=message, url=url)
        if message.user == self.user:
            notify(subject, 'tickets/mail_support_reply.txt', self.get_contacts(), ctx)
        if self.user and self.user.email:
            if message.staff_only and not self.user.has_perm('tickets.view_private_message'):
                return
            notify(subject, 'tickets/mail_user_reply.txt', [self.user.email], ctx)

    def __str__(self):
        return self.subject

    def get_absolute_url(self):
        return reverse('tickets:view', args=(self.id,))


class TicketNotifyAddress(models.Model):
    category = models.CharField(max_length=16, choices=CATEGORY_CHOICES)
    address = models.EmailField()


class TicketMessage(models.Model):
    ticket = models.ForeignKey(Ticket, related_name='message_set',
                               on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True,
                             on_delete=models.SET_NULL)
    remote_addr = models.GenericIPAddressField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    message = models.TextField()
    staff_only = models.BooleanField(default=False)

    class Meta:
        ordering = ('created',)

tickets/forms.py
from django import forms
from .models import TicketMessage, CATEGORY_CHOICES
from django.utils.translation import ugettext_lazy as _


class NewTicketForm(forms.Form):
    category = forms.ChoiceField(label=_("Category"), choices=CATEGORY_CHOICES)
    subject = forms.CharField(label=_("Subject"), min_length=1, max_length=100)
    message = forms.CharField(label=_("Message"), widget=forms.Textarea)


class ReplyForm(forms.ModelForm):
    class Meta:
        model = TicketMessage
        fields = ('message',)


class StaffReplyForm(forms.ModelForm):
    class Meta:
        model = TicketMessage
        fields = ('message', 'staff_only')

    staff_only = forms.BooleanField(label=_("Private"), required=False)

tickets/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http.response import HttpResponseNotFound
from django.utils import timezone
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils.translation import ugettext as _

from ccvpn.common import get_client_ip
from .models import Ticket, TicketMessage
from .forms import NewTicketForm, ReplyForm, StaffReplyForm


def common_context(request):
    context = {
        'open_n': Ticket.objects.filter(is_open=True, user=request.user).count(),
        'closed_n': Ticket.objects.filter(is_open=False, user=request.user).count(),
    }
    if request.user.has_perm('tickets.view_any_ticket'):
        context.update({
            'all_open_n': Ticket.objects.filter(is_open=True).count(),
            'all_closed_n': Ticket.objects.filter(is_open=False).count(),
        })
    return context


@login_required
def index(request, f=None, all=False):
    tickets = Ticket.objects

    if f == 'closed':
        tickets = tickets.filter(is_open=False)
    else:
        tickets = tickets.filter(is_open=True)

    if all is False or not request.user.has_perm('tickets.view_any_ticket'):
        tickets = tickets.filter(user=request.user)
        single_user = True
    else:
        single_user = False

    paginator = Paginator(tickets, 20)
    page = request.GET.get('page')
    try:
        tickets = paginator.page(page)
    except PageNotAnInteger:
        tickets = paginator.page(1)
    except EmptyPage:
        tickets = paginator.page(paginator.num_pages)

    context = dict(
        tickets=tickets,
        filter=f,
        single_user=single_user,
        title=_("Tickets"),
    )
    context.update(common_context(request))
    if not f:
        return render(request, 'tickets/index.html', context)
    else:
        return render(request, 'tickets/list.html', context)


@login_required
def new(request):
    context = common_context(request)
    context['title'] = _("New Ticket")
    if request.method != 'POST':
        context['form'] = NewTicketForm()
        return render(request, 'tickets/new.html', context)

    form = NewTicketForm(request.POST)

    if not form.is_valid():
        context['form'] = form
        return render(request, 'tickets/new.html', context)

    ticket = Ticket(category=form.cleaned_data['category'],
                    subject=form.cleaned_data['subject'],
                    user=request.user)
    ticket.save()

    firstmsg = TicketMessage(ticket=ticket, user=request.user,
                             message=form.cleaned_data['message'])

    if not request.user.is_staff:
        firstmsg.remote_addr = get_client_ip(request)

    firstmsg.save()

    ticket.notify_new(firstmsg)

    return redirect('tickets:view', id=ticket.id)


@login_required
def view(request, id):
    ticket = get_object_or_404(Ticket, id=id)

    view_any_ticket = request.user.has_perm('tickets.view_any_ticket')
    reply_any_ticket = request.user.has_perm('tickets.reply_any_ticket')

    if not view_any_ticket and ticket.user != request.user:
        return HttpResponseNotFound()

    if request.user.has_perm('tickets.view_private_message'):
        messages = ticket.message_set.all()
    else:
        messages = ticket.message_set.filter(staff_only=False)

    if request.method != 'POST':
        ctx = dict(
            staff_reply=request.user.has_perm('tickets.post_private_message'),
            ticket=ticket,
            ticket_messages=messages,
            form=ReplyForm(),
            title=_("Ticket:") + " " + ticket.subject,
        )
        ctx.update(common_context(request))
        return render(request, 'tickets/view.html', ctx)

    if not reply_any_ticket and ticket.user != request.user:
        return HttpResponseNotFound()

    if request.POST.get('close') or request.POST.get('button_close'):
        ticket.is_open = False
        ticket.closed = timezone.now()
        ticket.save()
        return redirect('tickets:view', id=ticket.id)

    if request.POST.get('reopen') or request.POST.get('button_reopen'):
        ticket.is_open = True
        ticket.save()
        return redirect('tickets:view', id=ticket.id)

    if request.user.has_perm('tickets.post_private_message'):
        form = StaffReplyForm(request.POST)
    else:
        form = ReplyForm(request.POST)

    if not form.is_valid():
        ctx = dict(
            staff_reply=request.user.has_perm('tickets.post_private_message'),
            ticket=ticket,
            ticket_messages=messages,
            form=form,
            title=_("Ticket:") + " " + ticket.subject,
        )
        ctx.update(common_context(request))
        return render(request, 'tickets/view.html', ctx)

    msg = TicketMessage(ticket=ticket, user=request.user,
                        **form.cleaned_data)

    if not request.user.is_staff:
        msg.remote_addr = get_client_ip(request)

    msg.save()

    if not ticket.is_open:
        ticket.is_open = True
        ticket.save()

    ticket.notify_reply(msg)

    return redirect('tickets:view', id=ticket.id)

templates/tickets/index.html
{% extends 'tickets/layout.html' %}
{% load i18n %}
{% load staticfiles %}

{% block tickets_content %}
<h1>{% trans 'Support' %}</h1>

{% url 'chat' as chat_url %}

<p>{% trans 'Before creating a ticket, please check if you question is convered in' %}
    <a href="/page/faq">{% trans 'the FAQ' %}</a>.
</p>
<p>{% blocktrans trimmed with chat_url as chat_url %}
    If you would prefer to talk us in real time, we have a 
    <a href="{{chat_url}}">live chat</a>.<br />
    You can also use your own IRC client on #ccrypto on chat.freenode.net.
    We are however not always online and you may have to wait.
    {% endblocktrans %}
</p>


{% if tickets %}
<h2>{% trans 'Your open tickets' %}</h2>
    <table class="admin-list">
        <thead>
            <tr>
                <td>#{% trans 'ID' %}</td>
                <td>{% trans 'Subject' %}</td>
                <td>{% trans 'Status' %}</td>
            </tr>
        </thead>
        <tbody>
            {% for ticket in tickets %}
                <tr>
                    <td>#{{ticket.id}}</td>
                    <td><a href="{% url 'tickets:view' ticket.id %}">{{ ticket.subject }}</a></td>
                    <td>{{ ticket.status_text }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    {% if tickets.has_previous or tickets.has_next %}
    <p class="pages">
        {% if tickets.has_previous %}
        <a href="?{{ filter }}&amp;page={{ tickets.previous_page_number }}">&lt;</a>
        {% endif %}
        <a href="?{{ filter }}&amp;page={{ tickets.number }}">{{ tickets.number }}</a>
        {% if tickets.has_next %}
            <a href="?{{ filter }}&amp;page={{ tickets.next_page_number }}">&gt;</a>
        {% endif %}
    </p>
    {% endif %}
{% endif %}
{% endblock %}

templates/tickets/layout.html
{% extends 'layout.html' %}
{% load i18n %}
{% load staticfiles %}

{% block content %}
<div class="page">
    <div class="left-menu">
        <p class="menu-title">{% trans 'Support' %}</p>
        <ul>
            <li><a href="/chat"><b>{% trans 'Live Chat' %}</b></a></li>
            <li><a href="/tickets/new"><b>{% trans 'New Ticket' %}</b></a></li>
            <li><a href="/tickets/open">{% trans 'Open Tickets' %}
                    {% if open_n > 0 %}({{open_n}}){% endif %}</a></li>
            <li><a href="/tickets/closed">{% trans 'Closed Tickets' %}</a></li>
            {% if perms.tickets.view_any_ticket %}
                <li><a href="/tickets/all_open">{% trans 'All Open' %}
                        {% if all_open_n > 0 %}({{all_open_n}}){% endif %}</a></li>
                <li><a href="/tickets/all_closed">{% trans 'All Closed' %}</a></li>
            {% endif %}
        </ul>
    </div>
    <div class="content">
        {% block tickets_content %}{% endblock %}
    </div>
</div>
{% endblock %}

templates/tickets/list.html
{% extends 'tickets/layout.html' %}
{% load i18n %}
{% load staticfiles %}

{% block tickets_content %}
<h1>{% trans 'Tickets' %}</h1>

{% if tickets %}
    <table class="admin-list">
        <thead>
            <tr>
                <td>#{% trans 'ID' %}</td>
                <td>{% trans 'Subject' %}</td>
                <td>{% trans 'Status' %}</td>
                {% if not single_user %}
                    <td>{% trans 'User' %}</td>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for ticket in tickets %}
                <tr>
                    <td>#{{ticket.id}}</td>
                    <td><a href="{% url 'tickets:view' ticket.id %}">{{ ticket.subject }}</a></td>
                    <td>{{ ticket.status_text }}</td>
                    {% if not single_user %}
                        {% if ticket.user %}
                            <td><a href="{% url 'admin:auth_user_change' ticket.user.id %}">
                                    {{ticket.user.username}}
                            </a></td>
                        {% else %}
                            <td>-</td>
                        {% endif %}
                    {% endif %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <p class="pages">
        {% if tickets.has_previous %}
        <a href="?{{ filter }}&amp;page={{ tickets.previous_page_number }}">&lt;</a>
        {% endif %}
        <a href="?{{ filter }}&amp;page={{ tickets.number }}">{{ tickets.number }}</a>
        {% if tickets.has_next %}
            <a href="?{{ filter }}&amp;page={{ tickets.next_page_number }}">&gt;</a>
        {% endif %}
    </p>
{% else %}
<p>{% trans 'No ticket to show.' %}</p>
{% endif %}
{% endblock %}

templates/tickets/new.html
{% extends 'tickets/layout.html' %}
{% load i18n %}
{% load staticfiles %}

{% block tickets_content %}
<div class="formpage">
    <h1>{% trans 'New Ticket' %}</h1>

    <form class="pure-form pure-form-stacked" action="" method="post">
        {% csrf_token %}
        {{ form }}

        <input type="submit" class="pure-button pure-button-primary" value="{% trans 'Open Ticket' %}" />
    </form>
</div>
{% endblock %}

templates/tickets/view.html
{% extends 'tickets/layout.html' %}
{% load i18n %}
{% load staticfiles %}

{% block tickets_content %}
<div class="formpage">
    <h1>{% trans 'Ticket:' %} {{ ticket.subject }}
        {% if not ticket.is_open %}
        <b>[{% trans 'closed' %}]</b>
        {% endif %}
    </h1>

    <div class="ticket-messages">
    {% for message in ticket_messages %}
        <div class="ticket-message
                    {% if ticket.user == message.user %} ticket-message-user
                    {% else %} ticket-message-staff {% endif %}
                    {% if message.staff_only %} ticket-message-private {% endif %}">
            <p class="ticket-message-author">
                {% if message.staff_only %}[{% trans "Private" %}]{% endif %}
                {% if ticket.user != message.user %} CCrypto Support - {% endif %}
                {{ message.user.username|default:'-' }}:
            </p>
            <p class="ticket-message-date">
                {% with created=message.created|date:'d/m/Y H:i' %}
                    {{ created }}
                {% endwith %}
            </p>
            <p class="ticket-message-content">
                {{ message.message | linebreaksbr | urlize }}
            </p>
        </div>
    {% endfor %}
    </div>

    <form class="pure-form pure-form-stacked" action="" method="post">
        {% csrf_token %}

        <label for="id_message">Message:</label>
        <textarea cols="40" id="id_message" name="message" rows="10"></textarea>

        {% if staff_reply %}
            <label for="id_staff_only">Private:</label>
            <input id="id_staff_only" name="staff_only" type="checkbox" />
        {% endif %}

        <input type="submit" class="pure-button pure-button-primary button-1-2" value="{% trans 'Reply' %}" />
        {% if ticket.is_open %}
                <input type="submit" class="pure-button button-1-2" name="close" value="{% trans 'Close Ticket' %}" />
        {% else %}
                <input type="submit" class="pure-button button-1-2" name="reopen" value="{% trans 'Re-open Ticket' %}" />
        {% endif %}
        </div>
    </form>
</div>
{% endblock %}